#!/usr/bin/env python

import sys
import pandas as pd

column_names = {
    "Date (LST)": "time",
    "CO": "epa-co",
    "NO2_AV": "epa-no2",
    "NO_AV": "epa-no",
    "NOx_AV": "epa-nox",
    "O3_AV": "epa-o3",
    "RH": "epa-humidity",
    "T": "epa-temperature",
}

if __name__ == "__main__":
    df = pd.read_csv(sys.stdin, delimiter="|")
    df.index = pd.to_datetime(df['Date (LST)'])#.tz_localize("LST").tz_convert("US/Pacific")
    df = df.sort_index()
    df = df[df["QC Name"] == "Valid"]
    df = df.pivot(columns='Parameter', values='Value')
    df = df.drop('WD', 1)
    df = df.rename(columns=column_names)
    df = df.dropna(how='any')
    df.index.names = ["datetime"]
    print(df.to_csv(index_label='datetime').strip())
