#!/usr/bin/env python
import pandas as pd
import numpy as np
import sys
from argparse import ArgumentParser
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('white')

def parse_args():
    argparser = ArgumentParser()

    argparser.add_argument('y1')
    argparser.add_argument('y2')

    return argparser.parse_args()

if __name__ == "__main__":
    args = parse_args()

    data = pd.read_csv(sys.stdin, index_col='time')
    data.index = pd.to_datetime(data.index).tz_localize('US/Pacific')

    data.plot(y=[args.y1, args.y2])
    plt.legend(loc='best')
    data['error'] = np.sqrt((data[args.y1] - data[args.y2])**2)
    data = data.groupby(pd.TimeGrouper(freq='W')).mean()
    data.plot(y='error')
    plt.show()
