#!/usr/bin/env python
import numpy as np
import pandas as pd
import sys
from argparse import ArgumentParser
import pickle

def parse_args():
    argparser = ArgumentParser()

    argparser.add_argument('model')
    argparser.add_argument('--start_date', default='2016-08-13')
    argparser.add_argument('--out_column', default='predictions')

    return argparser.parse_args()

if __name__ == "__main__":
    args = parse_args()

    with open(args.model, 'rb') as fp:
        (x, y, model) = pickle.load(fp)

    data = pd.read_csv(sys.stdin, index_col='datetime')
    data.index = pd.to_datetime(data.index).tz_localize('US/Pacific')

    data = data.ix[args.start_date:]

    X = data[x]
    y = data[y]
    data[args.out_column] = preds = model.predict(X)

    print("RMSE: %.3f" % np.sqrt(np.mean((preds - y) ** 2)), file=sys.stderr)
    print(data.to_csv(index_label='datetime'), end="")
